/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class infomosaic_securexml_SmartcardImpl */

#ifndef _Included_infomosaic_securexml_SmartcardImpl
#define _Included_infomosaic_securexml_SmartcardImpl
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     infomosaic_securexml_SmartcardImpl
 * Method:    CsetRID
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_infomosaic_securexml_SmartcardImpl_CsetRID
  (JNIEnv *, jobject, jstring);

/*
 * Class:     infomosaic_securexml_SmartcardImpl
 * Method:    CgetCN
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_SmartcardImpl_CgetCN
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     infomosaic_securexml_SmartcardImpl
 * Method:    CgetEmailAddress
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_SmartcardImpl_CgetEmailAddress
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     infomosaic_securexml_SmartcardImpl
 * Method:    CconnectToCard
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_infomosaic_securexml_SmartcardImpl_CconnectToCard
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_SmartcardImpl
 * Method:    CdisconnectFromCard
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_infomosaic_securexml_SmartcardImpl_CdisconnectFromCard
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_SmartcardImpl
 * Method:    CgetBloodTypeCode
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_SmartcardImpl_CgetBloodTypeCode
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_SmartcardImpl
 * Method:    CgetBranchOfServiceCode
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_SmartcardImpl_CgetBranchOfServiceCode
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_SmartcardImpl
 * Method:    CgetCHCCode
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_SmartcardImpl_CgetCHCCode
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_SmartcardImpl
 * Method:    CgetCHCEndDate
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_SmartcardImpl_CgetCHCEndDate
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_SmartcardImpl
 * Method:    CgetCadency
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_SmartcardImpl_CgetCadency
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_SmartcardImpl
 * Method:    CgetCardExpiryDate
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_SmartcardImpl_CgetCardExpiryDate
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_SmartcardImpl
 * Method:    CgetCardIssueDate
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_SmartcardImpl_CgetCardIssueDate
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_SmartcardImpl
 * Method:    CgetCommissaryCode
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_SmartcardImpl_CgetCommissaryCode
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_SmartcardImpl
 * Method:    CgetDateCacDataExpires
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_SmartcardImpl_CgetDateCacDataExpires
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_SmartcardImpl
 * Method:    CgetDateCacDataLoaded
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_SmartcardImpl_CgetDateCacDataLoaded
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_SmartcardImpl
 * Method:    CgetDateOfBirth
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_SmartcardImpl_CgetDateOfBirth
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_SmartcardImpl
 * Method:    CgetDirectCareCode
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_SmartcardImpl_CgetDirectCareCode
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_SmartcardImpl
 * Method:    CgetDirectCareEndDate
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_SmartcardImpl_CgetDirectCareEndDate
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_SmartcardImpl
 * Method:    CgetDoDContractorFunctionCode
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_SmartcardImpl_CgetDoDContractorFunctionCode
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_SmartcardImpl
 * Method:    CgetErrorMessage
 * Signature: (IJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_SmartcardImpl_CgetErrorMessage
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     infomosaic_securexml_SmartcardImpl
 * Method:    CgetExchangeCode
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_SmartcardImpl_CgetExchangeCode
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_SmartcardImpl
 * Method:    CgetFirstName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_SmartcardImpl_CgetFirstName
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_SmartcardImpl
 * Method:    CgetGenderCode
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_SmartcardImpl_CgetGenderCode
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_SmartcardImpl
 * Method:    CgetLastName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_SmartcardImpl_CgetLastName
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_SmartcardImpl
 * Method:    CgetMWRCode
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_SmartcardImpl_CgetMWRCode
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_SmartcardImpl
 * Method:    CgetMealPlanCode
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_SmartcardImpl_CgetMealPlanCode
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_SmartcardImpl
 * Method:    CgetMiddleName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_SmartcardImpl_CgetMiddleName
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_SmartcardImpl
 * Method:    CgetNonMedicalBenefitsEndDate
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_SmartcardImpl_CgetNonMedicalBenefitsEndDate
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_SmartcardImpl
 * Method:    CgetNonUSGovernmentAgencyCode
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_SmartcardImpl_CgetNonUSGovernmentAgencyCode
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_SmartcardImpl
 * Method:    CgetOrganDonorCode
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_SmartcardImpl_CgetOrganDonorCode
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_SmartcardImpl
 * Method:    CgetPayGrade
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_SmartcardImpl_CgetPayGrade
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_SmartcardImpl
 * Method:    CgetPayPlan
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_SmartcardImpl_CgetPayPlan
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_SmartcardImpl
 * Method:    CgetPersonDoDEDI
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_SmartcardImpl_CgetPersonDoDEDI
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_SmartcardImpl
 * Method:    CgetPersonIdentifier
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_SmartcardImpl_CgetPersonIdentifier
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_SmartcardImpl
 * Method:    CgetPersonIdentifierTypeCode
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_SmartcardImpl_CgetPersonIdentifierTypeCode
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_SmartcardImpl
 * Method:    CgetPersonnelCategoryCode
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_SmartcardImpl_CgetPersonnelCategoryCode
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_SmartcardImpl
 * Method:    CgetPersonnelEntitlementConditionTypeCode
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_SmartcardImpl_CgetPersonnelEntitlementConditionTypeCode
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_SmartcardImpl
 * Method:    CgetRank
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_SmartcardImpl_CgetRank
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_SmartcardImpl
 * Method:    CgetUSGovernmentAgencyCode
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_SmartcardImpl_CgetUSGovernmentAgencyCode
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_SmartcardImpl
 * Method:    Cinitialize
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_infomosaic_securexml_SmartcardImpl_Cinitialize
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_SmartcardImpl
 * Method:    ClogoffFromCard
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_infomosaic_securexml_SmartcardImpl_ClogoffFromCard
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_SmartcardImpl
 * Method:    ClogonToCard
 * Signature: (ILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_infomosaic_securexml_SmartcardImpl_ClogonToCard
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
