/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class infomosaic_securexml_Signature */

#ifndef _Included_infomosaic_securexml_Signature
#define _Included_infomosaic_securexml_Signature
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     infomosaic_securexml_Signature
 * Method:    createSignatureObject
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_infomosaic_securexml_Signature_createSignatureObject
  (JNIEnv *, jobject);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    destroySignatureObject
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_destroySignatureObject
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetEnvelopingFlag
 * Signature: (I)S
 */
JNIEXPORT jshort JNICALL Java_infomosaic_securexml_Signature_CgetEnvelopingFlag
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetEnvelopingFlag
 * Signature: (IS)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetEnvelopingFlag
  (JNIEnv *, jobject, jint, jshort);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetRecipientCertificateStore
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetRecipientCertificateStore
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetRecipientCertificateStore
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetRecipientCertificateStore
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetSignerCertificate
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetSignerCertificate
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetSignerCertificate
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetSignerCertificate
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetSignatureID
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetSignatureID
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetSignatureID
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetSignatureID
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetProperties
 * Signature: (III)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetProperties
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetProperties
 * Signature: (IIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetProperties
  (JNIEnv *, jobject, jint, jint, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetBase64EncodeXML
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_infomosaic_securexml_Signature_CgetBase64EncodeXML
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetBase64EncodeXML
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetBase64EncodeXML
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetBase64DecodeXML
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_infomosaic_securexml_Signature_CgetBase64DecodeXML
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetBase64DecodeXML
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetBase64DecodeXML
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetDocumentURI
 * Signature: (III)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetDocumentURI
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetDigestObjectStatus
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_infomosaic_securexml_Signature_CgetDigestObjectStatus
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetLanguage
 * Signature: (I)I
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetLanguage
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetLanguage
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetLanguage
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetSignatureStatus
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_infomosaic_securexml_Signature_CgetSignatureStatus
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetPhysicalSignatureUsage
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_infomosaic_securexml_Signature_CgetPhysicalSignatureUsage
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetPhysicalSignatureUsage
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetPhysicalSignatureUsage
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetPhysicalSignatureFile
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetPhysicalSignatureFile
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetPhysicalSignatureFile
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetPhysicalSignatureFile
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetCapturedSignatureFile
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetCapturedSignatureFile
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    Csign
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_Csign
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetIncludeCamResponse
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_infomosaic_securexml_Signature_CgetIncludeCamResponse
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetIncludeCamResponse
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetIncludeCamResponse
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsaveXMLSignature
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsaveXMLSignature
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    Cverify
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_infomosaic_securexml_Signature_Cverify
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetError
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetError
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetOverwriteFile
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetOverwriteFile
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CpFXExportCertificate
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CpFXExportCertificate
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CverifyDetached
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_infomosaic_securexml_Signature_CverifyDetached
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetLastError
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_infomosaic_securexml_Signature_CgetLastError
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetX509Certificate
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetX509Certificate
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CviewCertificate
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CviewCertificate
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetCertificateCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_infomosaic_securexml_Signature_CgetCertificateCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetCertificateInfo
 * Signature: (III)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetCertificateInfo
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetActiveCertificate
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_infomosaic_securexml_Signature_CsetActiveCertificate
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetSignedDocumentPath
 * Signature: (III)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetSignedDocumentPath
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetSignerSubject
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetSignerSubject
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetCertIssuer
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetCertIssuer
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetCertExpiry
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetCertExpiry
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetCertSerialNumber
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetCertSerialNumber
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CfileExists
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_infomosaic_securexml_Signature_CfileExists
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetFailedUriCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_infomosaic_securexml_Signature_CgetFailedUriCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetTotalUriCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_infomosaic_securexml_Signature_CgetTotalUriCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetFailedUriFullPath
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetFailedUriFullPath
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetFailedUriFullPath
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetFailedUriFullPath
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetFailedUri
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetFailedUri
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetSignatureCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_infomosaic_securexml_Signature_CgetSignatureCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsignXMLStr
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CsignXMLStr
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CreadAll
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CreadAll
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsaveXMLStr
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CsaveXMLStr
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsignHTML
 * Signature: (ILjava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CsignHTML
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsecureXMLVerify
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CsecureXMLVerify
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetCSP
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetCSP
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetSignedHTML
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetSignedHTML
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsignFile
 * Signature: (ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsignFile
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetSignedFileObject
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetSignedFileObject
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetStoreName
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetStoreName
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetStoreName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetStoreName
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsignXMLEnveloped
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CsignXMLEnveloped
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetVersion
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetVersion
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetLicenseStatus
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_infomosaic_securexml_Signature_CgetLicenseStatus
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetPropertyCount
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_infomosaic_securexml_Signature_CgetPropertyCount
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CviewAnyCertificate
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CviewAnyCertificate
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CselectActiveCertificate
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CselectActiveCertificate
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CverifyXMLStr
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_infomosaic_securexml_Signature_CverifyXMLStr
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetActivePFXFileCert
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CsetActivePFXFileCert
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CpFXExportActiveCertificate
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CpFXExportActiveCertificate
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetHostName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetHostName
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetTimeStampURL
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetTimeStampURL
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetTimeStampURL
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetTimeStampURL
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetTimeStamping
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_infomosaic_securexml_Signature_CgetTimeStamping
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetTimeStamping
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetTimeStamping
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetHostOsType
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_infomosaic_securexml_Signature_CgetHostOsType
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetCrlChecking
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_infomosaic_securexml_Signature_CgetCrlChecking
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetCrlChecking
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetCrlChecking
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetSigCertStatus
 * Signature: (IILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_infomosaic_securexml_Signature_CgetSigCertStatus
  (JNIEnv *, jobject, jint, jint, jstring, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CverifyX509CertCRL
 * Signature: (ILjava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_infomosaic_securexml_Signature_CverifyX509CertCRL
  (JNIEnv *, jobject, jint, jstring, jstring, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CverifyPFXCertCRL
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_infomosaic_securexml_Signature_CverifyPFXCertCRL
  (JNIEnv *, jobject, jint, jstring, jstring, jstring, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetAddWindowImage
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_infomosaic_securexml_Signature_CgetAddWindowImage
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetAddWindowImage
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetAddWindowImage
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetCRLLocation
 * Signature: (I[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetCRLLocation
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CverifyActiveCertificate
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_infomosaic_securexml_Signature_CverifyActiveCertificate
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetCertificatePolicy
 * Signature: (I[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetCertificatePolicy
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetAuthorityConstrainedPolicy
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_infomosaic_securexml_Signature_CgetAuthorityConstrainedPolicy
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetUserConstrainedPolicy
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_infomosaic_securexml_Signature_CgetUserConstrainedPolicy
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetCertificatePolicyChecking
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetCertificatePolicyChecking
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetCertificateChainValidation
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetCertificateChainValidation
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetCertificatePathLengthChecking
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetCertificatePathLengthChecking
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetConfigFileName
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetConfigFileName
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetDoDCompliance
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetDoDCompliance
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetCertificatePolicyExplicit
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_infomosaic_securexml_Signature_CgetCertificatePolicyExplicit
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetCertificatePolicyExplicit
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetCertificatePolicyExplicit
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetCertificateTrustExplicit
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetCertificateTrustExplicit
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsignXMLXpathStr
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CsignXMLXpathStr
  (JNIEnv *, jobject, jint, jstring, jstring, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetUseHMAC
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_infomosaic_securexml_Signature_CgetUseHMAC
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetUseHMAC
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetUseHMAC
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetHMACPassword
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetHMACPassword
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetHMACPassword
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetHMACPassword
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CchangeOrAddProperty
 * Signature: (ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CchangeOrAddProperty
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetDetailedVerificationFlag
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetDetailedVerificationFlag
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CcaptureLiveSignature
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CcaptureLiveSignature
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsignDataStr
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CsignDataStr
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetExcludeSignerCertificate
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetExcludeSignerCertificate
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CcoSignXMLStr
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CcoSignXMLStr
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CcoSignFile
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CcoSignFile
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsignFiles
 * Signature: (I[Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CsignFiles
  (JNIEnv *, jobject, jint, jobjectArray, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetRecipientCertificates
 * Signature: (I[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetRecipientCertificates
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CencryptStr
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CencryptStr
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CdecryptStr
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CdecryptStr
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CencryptFile
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CencryptFile
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CdecryptFile
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CdecryptFile
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetTrustedRoots
 * Signature: (I[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetTrustedRoots
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetRecipientCertificateFiles
 * Signature: (I[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetRecipientCertificateFiles
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetDetachedObjects
 * Signature: (I[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetDetachedObjects
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetAttachedObjects
 * Signature: (I[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetAttachedObjects
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CreadAllBase64
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CreadAllBase64
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetDecryptionPFXCertFile
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetDecryptionPFXCertFile
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetDecryptUsingPFXFileCert
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetDecryptUsingPFXFileCert
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetDecryptionPFXPassword
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetDecryptionPFXPassword
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetXpathNamespace
 * Signature: (I[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetXpathNamespace
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetCamServerHost
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetCamServerHost
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetCamServerHost
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetCamServerHost
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetCamServerPort
 * Signature: (I)S
 */
JNIEXPORT jshort JNICALL Java_infomosaic_securexml_Signature_CgetCamServerPort
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetCamServerPort
 * Signature: (IS)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetCamServerPort
  (JNIEnv *, jobject, jint, jshort);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetUseCam
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_infomosaic_securexml_Signature_CgetUseCam
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetUseCam
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetUseCam
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetAgencyId
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetAgencyId
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetAgencyId
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetAgencyId
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetCamValidationResponse
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetCamValidationResponse
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetSigPropValueByName
 * Signature: (IILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetSigPropValueByName
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    Cbase64DecodeBufferToFile
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_Cbase64DecodeBufferToFile
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    Cbase64DecodeFileToFile
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_Cbase64DecodeFileToFile
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgunZipFile
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgunZipFile
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetCertSerialNumberFormat
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_infomosaic_securexml_Signature_CgetCertSerialNumberFormat
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetCertSerialNumberFormat
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetCertSerialNumberFormat
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsecureXMLVerifyFileToBuffer
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CsecureXMLVerifyFileToBuffer
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsecureXMLVerifyFileToFile
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CsecureXMLVerifyFileToFile
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CdeleteSignatureFromXMLStr
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CdeleteSignatureFromXMLStr
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CdeleteSignatureFromFile
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CdeleteSignatureFromFile
  (JNIEnv *, jobject, jint, jstring, jstring, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetAllowedCertIssuerNames
 * Signature: (I[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetAllowedCertIssuerNames
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetCRLCacheDbConnectionString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetCRLCacheDbConnectionString
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetCRLCacheDbConnectionString
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetCRLCacheDbConnectionString
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetUseCRLCache
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_infomosaic_securexml_Signature_CgetUseCRLCache
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetUseCRLCache
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetUseCRLCache
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetCRLCacheTimeoutInMinutes
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetCRLCacheTimeoutInMinutes
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetCanonicalizationMethod
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetCanonicalizationMethod
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetNetscapeStorePassword
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetNetscapeStorePassword
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetNetscapeStorePassword
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetNetscapeStorePassword
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetActivePEMFileCert
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CsetActivePEMFileCert
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetSecureXMLPath
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetSecureXMLPath
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetSignedDocumentCount
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_infomosaic_securexml_Signature_CgetSignedDocumentCount
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsignXMLByteArray
 * Signature: (I[BLjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_infomosaic_securexml_Signature_CsignXMLByteArray
  (JNIEnv *, jobject, jint, jbyteArray, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsaveXMLByteArray
 * Signature: (I[BLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CsaveXMLByteArray
  (JNIEnv *, jobject, jint, jbyteArray, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CreadAllByteArray
 * Signature: (ILjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_infomosaic_securexml_Signature_CreadAllByteArray
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CverifyXMLByteArray
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_infomosaic_securexml_Signature_CverifyXMLByteArray
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsecureXMLVerifyByteArray
 * Signature: (I[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_infomosaic_securexml_Signature_CsecureXMLVerifyByteArray
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsignXMLXpathByteArray
 * Signature: (I[BLjava/lang/String;Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_infomosaic_securexml_Signature_CsignXMLXpathByteArray
  (JNIEnv *, jobject, jint, jbyteArray, jstring, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsignXMLEnvelopedByteArray
 * Signature: (I[BLjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_infomosaic_securexml_Signature_CsignXMLEnvelopedByteArray
  (JNIEnv *, jobject, jint, jbyteArray, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    Cbase64DecodeByteArrayToFile
 * Signature: (I[BLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_Cbase64DecodeByteArrayToFile
  (JNIEnv *, jobject, jint, jbyteArray, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    Cbase64DecodeByteArrayToByteArray
 * Signature: (I[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_infomosaic_securexml_Signature_Cbase64DecodeByteArrayToByteArray
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    Cbase64EncodeByteArrayToByteArray
 * Signature: (I[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_infomosaic_securexml_Signature_Cbase64EncodeByteArrayToByteArray
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    Cbase64EncodeByteArrayToFile
 * Signature: (I[BLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_Cbase64EncodeByteArrayToFile
  (JNIEnv *, jobject, jint, jbyteArray, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    Cbase64EncodeStrToFile
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_Cbase64EncodeStrToFile
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    Cbase64EncodeStrToStr
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_Cbase64EncodeStrToStr
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetActivePFXB64Data
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CsetActivePFXB64Data
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetFloatingLicense
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetFloatingLicense
  (JNIEnv *env, jobject _this, jint sigObjIndex);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetFloatingLicense
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetFloatingLicense
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetLicensedUserCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_infomosaic_securexml_Signature_CgetLicensedUserCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetIncludeCRLInSignature
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetIncludeCRLInSignature
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetUsedCRLList
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_infomosaic_securexml_Signature_CgetUsedCRLList
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetErrorDetail
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetErrorDetail
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetPhysicalSignatureB64Str
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetPhysicalSignatureB64Str
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetSignedInfoDigest
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetSignedInfoDigest
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetX509CertificateChain
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetX509CertificateChain
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetSignerCertificateChain
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetSignerCertificateChain
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetSignatureImageId
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetSignatureImageId
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetSignatureImageId
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetSignatureImageId
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsignSignedInfoDigest
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CsignSignedInfoDigest
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CapplySignatureValue
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CapplySignatureValue
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetSignedInfoDigestFromByteArray
 * Signature: (I[BLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetSignedInfoDigestFromByteArray
  (JNIEnv *, jobject, jint, jbyteArray, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CapplySignatureValueGetByteArray
 * Signature: (ILjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_infomosaic_securexml_Signature_CapplySignatureValueGetByteArray
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetSignedDocumentB64Str
 * Signature: (III)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetSignedDocumentB64Str
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetSignedDocumentByteArray
 * Signature: (III)[B
 */
JNIEXPORT jbyteArray JNICALL Java_infomosaic_securexml_Signature_CgetSignedDocumentByteArray
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetCertValidationTransactionId
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetCertValidationTransactionId
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetCertValidationTransactionId
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetCertValidationTransactionId
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetIgnoreIncompleteSignature
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_infomosaic_securexml_Signature_CgetIgnoreIncompleteSignature
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetIgnoreIncompleteSignature
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetIgnoreIncompleteSignature
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetSignatureIndexToVerify
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_infomosaic_securexml_Signature_CgetSignatureIndexToVerify
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetSignatureIndexToVerify
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetSignatureIndexToVerify
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetUseOcsp
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_infomosaic_securexml_Signature_CgetUseOcsp
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetUseOcsp
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetUseOcsp
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetOcspTrustedRespSignerCertPath
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetOcspTrustedRespSignerCertPath
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetOcspTrustedRespSignerCertPath
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetOcspTrustedRespSignerCertPath
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetOcspReqSignerPFXCertPath
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetOcspReqSignerPFXCertPath
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetOcspReqSignerPFXCertPath
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetOcspReqSignerPFXCertPath
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetOcspReqSignerPFXCertPassword
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetOcspReqSignerPFXCertPassword
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetOcspReqSignerPFXCertPassword
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetOcspReqSignerPFXCertPassword
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetOcspResponderURL
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetOcspResponderURL
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetOcspResponderURL
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetOcspResponderURL
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetOcspTextResponse
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetOcspTextResponse
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetOcspB64Response
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetOcspB64Response
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetCertRevocationDate
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_infomosaic_securexml_Signature_CgetCertRevocationDate
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CgetIncludeOcspResponse
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_infomosaic_securexml_Signature_CgetIncludeOcspResponse
  (JNIEnv *, jobject, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetIncludeOcspResponse
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetIncludeOcspResponse
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetProxyHost
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetProxyHost
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetProxyPort
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetProxyPort
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetProxyUserName
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetProxyUserName
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetProxyPassword
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetProxyPassword
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     infomosaic_securexml_Signature
 * Method:    CsetInclusiveNamespacePrefixList
 * Signature: (I[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_infomosaic_securexml_Signature_CsetInclusiveNamespacePrefixList
  (JNIEnv *, jobject, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
